complete hardening

diff --git a/services/inference/Dockerfile.cpu b/services/inference/Dockerfile.cpu
--- a/services/inference/Dockerfile.cpu
+++ b/services/inference/Dockerfile.cpu
@@ -3,7 +3,7 @@
 FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS base
 
 ARG PYTHON_VERSION=3.12
-RUN microdnf upgrade -y \
+RUN microdnf update -y \
     && microdnf install -y python${PYTHON_VERSION} \
     python${PYTHON_VERSION}-pip \
     python${PYTHON_VERSION}-wheel \
@@ -22,35 +22,36 @@ FROM base AS tsfm-install
 ENV CUDA_VISIBLE_DEVICES=""
 
 # Image hardening start
+COPY --chmod=755 ImageHardening/* /remediation/
+RUN sh /remediation/installRemediationTools.sh \
+&& sh /remediation/remediation-script.sh \
+&& sh /remediation/removeRemediationTools.sh \
+&& rm -f /remediation/*.sh
+# # Image hardening stop
 
-COPY ImageHardening/* microservice_base_docker_image/scripts/common/
+# USER tsfm
 
+# ENV HOME=/home/tsfm
+# ENV PATH=${HOME}/.venv/bin:${PATH}
+# ENV POETRY_VIRTUALENVS_IN_PROJECT=1
+# ENV HF_HOME=/tmp
+# ENV PROMETHEUS_MULTIPROC_DIR=${HOME}/prometheus_metrics
 
-# Image hardening stop
+# ARG CODEDIR
+# COPY --chown=tsfm:tsfm --chmod=755 ${CODEDIR}/* ${HOME}/${CODEDIR}/
+# COPY --chown=tsfm:tsfm --chmod=755 pyproject.toml poetry.lock ${CODEDIR} ${HOME}
 
-USER tsfm
+# WORKDIR ${HOME}
 
-ENV HOME=/home/tsfm
-ENV PATH=${HOME}/.venv/bin:${PATH}
-ENV POETRY_VIRTUALENVS_IN_PROJECT=1
-ENV HF_HOME=/tmp
-ENV PROMETHEUS_MULTIPROC_DIR=${HOME}/prometheus_metrics
+# RUN python${PYTHON_VERSION} -m venv --upgrade-deps ${HOME}/.venv \
+# && pip install --no-cache-dir poetry \
+# && poetry install --no-cache \
+# && pip uninstall -y torch \
+# && for p in $(pip list | grep nvidia | cut -d " " -f1); do pip uninstall -y $p; done \
+# && pip install --no-cache-dir https://download.pytorch.org/whl/cpu/torch-2.6.0%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=59e78aa0c690f70734e42670036d6b541930b8eabbaa18d94e090abf14cc4d91 \
+# && rm -rf ${HOME}/.cache \
+# && mkdir ${HOME}/prometheus_metrics
 
-ARG CODEDIR
-COPY --chown=tsfm:tsfm --chmod=755 ${CODEDIR}/* ${HOME}/${CODEDIR}/
-COPY --chown=tsfm:tsfm --chmod=755 pyproject.toml poetry.lock ${CODEDIR} ${HOME}
-
-WORKDIR ${HOME}
-
-RUN python${PYTHON_VERSION} -m venv --upgrade-deps ${HOME}/.venv \
-&& pip install --no-cache-dir poetry \
-&& poetry install --no-cache \
-&& pip uninstall -y torch \
-&& for p in $(pip list | grep nvidia | cut -d " " -f1); do pip uninstall -y $p; done \
-&& pip install --no-cache-dir https://download.pytorch.org/whl/cpu/torch-2.6.0%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=59e78aa0c690f70734e42670036d6b541930b8eabbaa18d94e090abf14cc4d91 \
-&& rm -rf ${HOME}/.cache \
-&& mkdir ${HOME}/prometheus_metrics
-
-HEALTHCHECK CMD curl --fail http://localhost:8000/healthcheck || exit 1
+# HEALTHCHECK CMD curl --fail http://localhost:8000/healthcheck || exit 1
 
 
